
// Imports from library.
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 * @author ZoneSix   areazone6@gmail.com
 * @date April 3, 2015
 * @version 2.0
 */

public class MainFrame extends javax.swing.JFrame {
    
    // Creates a new Image 'icon' and assigns it an image.
    Image icon =(new ImageIcon(getClass().getResource("universal_dice_icon_64x.png"))).getImage();

    // Creates new form MainFrame
    public MainFrame() {
        
        initComponents();           // Calls the 'initComponents' method.
        this.setIconImage(icon);    // Sets the frames icon image to 'icon' on start.
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel1 = new MainPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuMenu = new javax.swing.JMenu();
        itemExit = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        itemHelp = new javax.swing.JMenuItem();
        menuSep = new javax.swing.JPopupMenu.Separator();
        itemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Universal Dice");
        setResizable(false);

        menuMenu.setText("Menu");
        menuMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuMenu.setIconTextGap(8);

        itemExit.setText("Exit");
        itemExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        itemExit.setIconTextGap(5);
        itemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemExitActionPerformed(evt);
            }
        });
        menuMenu.add(itemExit);

        jMenuBar1.add(menuMenu);

        menuHelp.setText("Help");
        menuHelp.setIconTextGap(8);

        itemHelp.setText("Show Help");
        itemHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemHelpActionPerformed(evt);
            }
        });
        menuHelp.add(itemHelp);
        menuHelp.add(menuSep);

        itemAbout.setText("About");
        itemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAboutActionPerformed(evt);
            }
        });
        menuHelp.add(itemAbout);

        jMenuBar1.add(menuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleName("Universal_Dice");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAboutActionPerformed
        
        mainPanel1.aboutDialog.setIconImage(icon);  // Sets the dialogs icon image to 'icon'.
        mainPanel1.aboutDialog.setSize(250, 245);   // Sets the dialogs size
        
        // This block gets the MainFrame's location and calculates the center of it.
        // Then it calculates 'aboutDialog's center and sets the location of it so it's center with the MainFrame.
        mainPanel1.aboutDialog.setLocation(
                this.getX() + this.getSize().width / 2 - mainPanel1.aboutDialog.getSize().width / 2,
                this.getY() + this.getSize().height / 2 - mainPanel1.aboutDialog.getSize().height / 2 );
        
        mainPanel1.aboutDialog.setVisible(true);    // Opens the 'aboutDialog'.
        
    }//GEN-LAST:event_itemAboutActionPerformed

    private void itemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemExitActionPerformed
        
        System.exit(0); // Exits the program.
        
    }//GEN-LAST:event_itemExitActionPerformed

    private void itemHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemHelpActionPerformed
        
        mainPanel1.helpFrame.setIconImage(icon);    // Sets the frames icon image to 'icon'.
        mainPanel1.helpFrame.setSize(423, 400);     // Sets the frames size
        
        // This block gets the MainFrame's location and calculates the center of it.
        // Then it calculates 'helpFrame's center and sets the location of it so it's center with the MainFrame.
        mainPanel1.helpFrame.setLocation(
                this.getX() + this.getSize().width / 2 - mainPanel1.helpFrame.getSize().width / 2,
                this.getY() + this.getSize().height / 2 - mainPanel1.helpFrame.getSize().height / 2 );
        
        mainPanel1.helpFrame.setVisible(true);  // Opens the 'helpFrame'.
        
    }//GEN-LAST:event_itemHelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAbout;
    private javax.swing.JMenuItem itemExit;
    private javax.swing.JMenuItem itemHelp;
    private javax.swing.JMenuBar jMenuBar1;
    private MainPanel mainPanel1;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenu menuMenu;
    private javax.swing.JPopupMenu.Separator menuSep;
    // End of variables declaration//GEN-END:variables
}
